name: Build MSP430 Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build with CCS
        uses: uoohyo/action-ccstudio-ide@v20.5.1.00012
        with:
          project-path: fw/msp430/wulpus_msp430_firmware
          project-name: wulpus_msp430_firmware
          build-config: ${{ matrix.configuration }}
          components: PF_MSP430

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware_${{ matrix.configuration }}
          path: fw/msp430/wulpus_msp430_firmware/${{ matrix.configuration }}/firmware.out
